package by.epamjwd.mobile.controller.repository;

public class ParameterName {

	public static final String LOGIN = "login";
	public static final String PASSWORD = "password";
	public static final String PASSPORT = "passport";
	public static final String ID = "id";
	public static final String PHONE = "phone";
	public static final String FIRST_NAME = "first_name";
	public static final String MIDDLE_NAME = "middle_name";
	public static final String LAST_NAME = "last_name";
	public static final String SUBSCRIBER_FIRST_NAME = "subscriber_first_name";
	public static final String SUBSCRIBER_MIDDLE_NAME = "subscriber_middle_name";
	public static final String SUBSCRIBER_LAST_NAME = "subscriber_last_name";
	public static final String EMAIL = "email";
	public static final String CALCULATOR_WITHIN_NETWORK = "within_network";
	public static final String CALCULATOR_OTHER_NETWORKS = "other_networks";
	public static final String CALCULATOR_ABROAD = "abroad";
	public static final String CALCULATOR_VIDEOCALL = "videocall";
	public static final String CALCULATOR_SMS = "sms";
	public static final String CALCULATOR_MMS = "mms";
	public static final String CALCULATOR_INTERNET = "internet";
	public static final String PLAN_ID = "plan_id";
	public static final String HEADER_REFER = "referer";
	public static final String SESSION_LOCALE = "session_locale";
	public static final String CUSTOMER = "customer";
	public static final String NEW_STATUS = "new_status";
	public static final String PASSWORD1 = "password1";
	public static final String PASSWORD2 = "password2";
	public static final String ENTERED_CODE = "entered_code";
	public static final String COMMAND = "command";
	public static final String NAME = "name";
	public static final String DESCRIPTION = "description";
	public static final String REGULAR_PAYMENT = "regular_payment";
	public static final String UPFRONT_PAYMENT = "upfront_payment";
	public static final String WITHIN_NETWORK = "within_network";
	public static final String OTHER_NETWORKS = "other_networks";
	public static final String ABROAD = "abroad";
	public static final String VIDEOCALL = "videocall";
	public static final String SMS = "sms";
	public static final String MMS = "mms";
	public static final String INTERNET = "internet";
	public static final String TARIFF = "tariff";
	public static final String TITLE = "title";
	public static final String LEAD = "lead";
	public static final String TEXT = "text";
	public static final String CONSULTANT_FIRST_NAME = "consultant_first_name";
	public static final String CONSULTANT_MIDDLE_NAME = "consultant_middle_name";
	public static final String CONSULTANT_LAST_NAME = "consultant_last_name";
	public static final String OLD_PASSWORD = "old_password";
	public static final String NEW_PASSWORD1 = "new_password1";
	public static final String NEW_PASSWORD2 = "new_password2";
}
